- id: go-imports
  name: "go imports"
  entry: run-go-imports.sh
  types: [go]
  language: "script"
  description: "Runs `goimports`, requires golang"
- id: go-cyclo
  name: "go-cyclo"
  entry: run-go-cyclo.sh
  types: [go]
  language: "script"
  description: "Runs `gocyclo`, requires https://github.com/fzipp/gocyclo"
  args: [-over=15]
- id: golangci-lint
  name: "golangci-lint"
  entry: run-golangci-lint.sh
  types: [go]
  language: "script"
  pass_filenames: false
  description: "Runs `golangci-lint`, requires https://github.com/golangci/golangci-lint"
- id: go-unit-tests
  name: "go-unit-tests"
  entry: run-go-unit-tests.sh
  pass_filenames: false
  types: [go]
  language: "script"
  description: "Runs `go test`"
- id: go-build
  name: "go-build"
  entry: run-go-build.sh
  pass_filenames: false
  types: [go]
  language: "script"
  description: "Runs `go build`, requires golang"
- id: go-generate
  name: "go-generate"
  entry: run-go-generate.sh
  pass_filenames: false
  types: [go]
  language: "script"
  description: "Runs `go generate`, requires golang"
- id: go-mod-tidy
  name: "go-mod-tidy"
  entry: run-go-mod-tidy.sh
  pass_filenames: false
  language: "script"
  description: "Runs `go mod tidy -v`, requires golang"
